name: "Generate Release Notes"
description: "Generate release notes from merged PRs with specific labels"

inputs:
  package_name:
    description: "Package name (used for tag matching and label filtering)"
    required: true
  version:
    description: "Release version"
    required: true

outputs:
  notes:
    description: "Generated release notes in markdown format"
    value: ${{ steps.release_notes.outputs.notes }}

runs:
  using: "composite"
  steps:
    - name: Generate release notes
      id: release_notes
      shell: bash
      run: |
        PREV_TAG=$(git describe --tags --match "${{ inputs.package_name }}@*" --abbrev=0 HEAD^ 2>/dev/null || echo "")

        if [ -z "$PREV_TAG" ]; then
          echo "No previous tag found, using initial commit"
          COMMITS=$(git rev-list --max-parents=0 HEAD)
        else
          COMMITS="${PREV_TAG}..HEAD"
        fi

        echo "Fetching PRs with label '${{ inputs.package_name }}' between $PREV_TAG and HEAD"

        PRS=$(gh pr list \
          --state merged \
          --limit 100 \
          --search "${COMMITS}" \
          --json title,number \
          --label "${{ inputs.package_name }}" \
          --jq '.[] | "- \(.title) (#\(.number))"')

        if [ -z "$PRS" ]; then
          echo "No PRs found with label '${{ inputs.package_name }}'"
          RELEASE_NOTES="## Release ${{ inputs.version }}\n\nNo changes in this release."
        else
          RELEASE_NOTES="## Release ${{ inputs.version }}\n\n### Changes\n\n$PRS"
        fi

        echo "notes<<EOF" >> $GITHUB_OUTPUT
        echo -e "$RELEASE_NOTES" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ github.token }}
